version: '3'

services:

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    ports:
      - 8080:80
    networks:
      - nextcloud_network
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: unless-stopped

volumes:
  nextcloud:
  db:

networks:
  nextcloud_network:
